# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-11-03 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20161201_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
